# Use nginx as the base image
FROM nginx

# Remove the default nginx configuration file
RUN rm /etc/nginx/conf.d/default.conf

# Copy the proxy configuration file into the container
COPY statsd/proxy.conf /etc/nginx/conf.d/

# Expose the port the proxy is listening on
EXPOSE 80
